[package]
name = "schafkopf_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.24.1"
strum_macros = "0.24.1"
rand = "0.8.5"

[dev-dependencies]
proptest = "1.0.0"